---

sudo: required
dist: trusty

language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'

branches:
  only:
    - develop
    - master

install:
  - pip install coveralls nose flake8
  - python setup.py install

script:
  - flake8 .
  - python setup.py nosetests

after_success:
  coveralls
